/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sena Gül KORKMAZ
 */
public class giriş extends javax.swing.JFrame {

    /**
     * Creates new form giriş
     */
    public giriş() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        doktorbutton = new javax.swing.JButton();
        hemsirebutton = new javax.swing.JButton();
        hastaBakicibutton = new javax.swing.JButton();
        temiziPersonelibutton = new javax.swing.JButton();
        hastaKayitbutton = new javax.swing.JButton();
        stajyerbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SEVGİ HASTANESİ");

        doktorbutton.setBackground(new java.awt.Color(204, 153, 255));
        doktorbutton.setText("DOKTOR GİRİŞ");
        doktorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doktorbuttonActionPerformed(evt);
            }
        });

        hemsirebutton.setBackground(new java.awt.Color(204, 153, 255));
        hemsirebutton.setText("HEMŞİRE GİRİŞ");
        hemsirebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hemsirebuttonActionPerformed(evt);
            }
        });

        hastaBakicibutton.setBackground(new java.awt.Color(204, 153, 255));
        hastaBakicibutton.setText("HASTA BAKICI GİRİŞ");
        hastaBakicibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaBakicibuttonActionPerformed(evt);
            }
        });

        temiziPersonelibutton.setBackground(new java.awt.Color(204, 153, 255));
        temiziPersonelibutton.setText("TEMİZLİK PERSONELİ GİRİŞ");
        temiziPersonelibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temiziPersonelibuttonActionPerformed(evt);
            }
        });

        hastaKayitbutton.setBackground(new java.awt.Color(204, 153, 255));
        hastaKayitbutton.setText("HASTA KAYIT GİRİŞ");
        hastaKayitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hastaKayitbuttonActionPerformed(evt);
            }
        });

        stajyerbutton.setBackground(new java.awt.Color(204, 153, 255));
        stajyerbutton.setText("STAJYER GİRİŞ");
        stajyerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stajyerbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hemsirebutton)
                            .addComponent(doktorbutton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(hastaBakicibutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(temiziPersonelibutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(hastaKayitbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(stajyerbutton)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(doktorbutton)
                .addGap(18, 18, 18)
                .addComponent(hemsirebutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hastaBakicibutton)
                .addGap(18, 18, 18)
                .addComponent(temiziPersonelibutton)
                .addGap(18, 18, 18)
                .addComponent(hastaKayitbutton)
                .addGap(18, 18, 18)
                .addComponent(stajyerbutton)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doktorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doktorbuttonActionPerformed
        doktorGirisSayfasi dgs = new doktorGirisSayfasi();
        dgs.setVisible(true);
    }//GEN-LAST:event_doktorbuttonActionPerformed

    private void hemsirebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hemsirebuttonActionPerformed
        hemsireGirisSayfasi hgs = new hemsireGirisSayfasi();
        hgs.setVisible(true);
    }//GEN-LAST:event_hemsirebuttonActionPerformed

    private void hastaKayitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaKayitbuttonActionPerformed
        hastaKayitGiris hkg = new hastaKayitGiris();
        hkg.setVisible(true);
    }//GEN-LAST:event_hastaKayitbuttonActionPerformed

    private void stajyerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stajyerbuttonActionPerformed
        stajyerGiris sg = new stajyerGiris();
        sg.setVisible(true);
    }//GEN-LAST:event_stajyerbuttonActionPerformed

    private void hastaBakicibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hastaBakicibuttonActionPerformed
        hastaBakiciGiris hbg = new hastaBakiciGiris();
        hbg.setVisible(true);
    }//GEN-LAST:event_hastaBakicibuttonActionPerformed

    private void temiziPersonelibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temiziPersonelibuttonActionPerformed
        temizlikPersonelGiris tpg = new temizlikPersonelGiris();
        tpg.setVisible(true);
    }//GEN-LAST:event_temiziPersonelibuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giriş.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giriş.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giriş.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giriş.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giriş().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doktorbutton;
    private javax.swing.JButton hastaBakicibutton;
    private javax.swing.JButton hastaKayitbutton;
    private javax.swing.JButton hemsirebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton stajyerbutton;
    private javax.swing.JButton temiziPersonelibutton;
    // End of variables declaration//GEN-END:variables
}
